---
# variables for port forwarding - dns update
dns_update_cron_schedule: '*/15 * * * *'
dns_update_cron_user: root

# api.upribox.org certificate
ssl_pinning_path: "/usr/local/etc/upri-filter-update/update-server.pem"

# client cert for DNS updates
cert_dns_path: "/usr/local/etc/credentials.pem"

# port and protocol for openvpn server
vpn_port: "{{ default_settings.vpn.connection.port if not (ansible_local is defined and ansible_local.vpn is defined and ansible_local.vpn.connection is defined) else ansible_local.vpn.connection.port | default(default_settings.vpn.connection.port) }}"
vpn_protocol: "{{ default_settings.vpn.connection.protocol if not (ansible_local is defined and ansible_local.vpn is defined and ansible_local.vpn.connection is defined) else ansible_local.vpn.connection.protocol | default(default_settings.vpn.connection.protocol) }}"