---
- hosts: upriboxes_pull
  remote_user: "{{ remote_user }}"
  become: yes
  become_method: sudo
  roles:
    - { role: common, tags: ["common"] }
    - { role: upri_config, tags: ["upri_config"] }
    - { role: iptables, tags: ["iptables"] }
    - { role: unattended_upgrades, tags: ["unattended_upgrades"] }
    - { role: wlan, tags: ["wlan"] }
    - { role: dns, tags: ["dns"] }
    - { role: vpn, tags: ["vpn"] }
    - { role: privoxy, tags: ["privoxy"] }
    - { role: squid, tags: ["squid"] }
    - { role: tor, tags: ["tor"] }
    - { role: dns_ninja, tags: ["dns_ninja"] }
    - { role: dns_unfiltered, tags: ["dns_unfiltered"] }
    - { role: arp, tags: ["arp"] }
    - { role: nginx, tags: ["nginx"] }
    - { role: fingerprinting, tags: ["fingerprinting"] }
    - { role: ntopng, tags: ["ntopng"] }
    - { role: django, tags: ["django"] }
  environment:
    PATH: "{{ root_path }}"
  post_tasks:
    - include: roles/ssh/main.yml
      tags: [toggle_ssh]

  # example for new ansible role style
  # several ansible versions (including 2.3.0.0) contain following bug:
  # https://github.com/ansible/ansible/issues/21890
  # include_role does not expose role variables to other roles (even with private option set to no)
  # block - always for error handling does not work with old role style
  # post_tasks are not executed on error - so not feasible

  # pre_tasks:
  #   - name: create recovery file
  #     file: path="{{ recovery_file }}" state=touch owner=root group=root mode=644
  #     tags: [create_recover]
  # tasks:
  #   - block:
  #       - include_role: name=common
  #         static: yes
  #         tags: common
  #         private: no
  #
  #       - include_role: name=upri_config
  #         static: yes
  #         tags: upri_config
  #         private: no
  #
  #       - include_role: name=iptables
  #         static: yes
  #         tags: iptables
  #         private: no
  #
  #       - include_role: name=unattended_upgrades
  #         static: yes
  #         tags: unattended_upgrades
  #         private: no
  #
  #       - include_role: name=wlan
  #         static: yes
  #         tags: wlan
  #         private: no
  #
  #       - include_role: name=dns
  #         static: yes
  #         tags: dns
  #         private: no
  #
  #       - include_role: name=vpn
  #         static: yes
  #         tags: vpn
  #         private: no
  #
  #       - include_role: name=privoxy
  #         static: yes
  #         tags: privoxy
  #         private: no
  #
  #       - include_role: name=squid
  #         static: yes
  #         tags: squid
  #         private: no
  #
  #       - include_role: name=tor
  #         static: yes
  #         tags: tor
  #         private: no
  #
  #       - include_role: name=dns_ninja
  #         static: yes
  #         tags: dns_ninja
  #         private: no
  #
  #       - include_role: name=dns_unfiltered
  #         static: yes
  #         tags: dns_unfiltered
  #         private: no
  #
  #       - include_role: name=arp
  #         static: yes
  #         tags: arp
  #         private: no
  #
  #       - include_role: name=nginx
  #         static: yes
  #         tags: nginx
  #         private: no
  #
  #       - include_role: name=fingerprinting
  #         static: yes
  #         tags: fingerprinting
  #         private: no
  #
  #       - include_role: name=ntopng
  #         static: yes
  #         tags: ntopng
  #         private: no
  #
  #       - include_role: name=django
  #         static: yes
  #         tags: django
  #         private: no
  #
  #     always:
  #       - name: delete recovery file
  #         file: path="{{ recovery_file }}" state=absent
  #         tags: [delete_recover]
  # post_tasks:
  #   - include: roles/ssh/main.yml
  #     tags: [toggle_ssh]
