---
  - include: ../../tor/tasks/tor_state.yml tags=toggle_tor

  - name: copy the iptables rules file
    template: src=iptables.upribox.ipv4 dest=/etc/iptables.upribox.ipv4 owner=root group=root mode=0644
    notify:
    - restore iptables
    tags:
    - toggle_tor