---
#jinja2 has to evaluate this string seperately, because it is not possible to just include this string in a "when" statement
- set_fact:
    dhcpd: "{{ default_settings.dhcpd.general.enabled if not (ansible_local is defined and ansible_local.dhcpd is defined and ansible_local.dhcpd.general is defined) else ansible_local.dhcpd.general.enabled | default(default_settings.dhcpd.general.enabled) }}"
