---
- include: ../../tor/tasks/tor_state.yml tags=ssid,toggle_tor

- name: install services
  apt: name={{ item }} state={{ apt_target_state }} force=yes update_cache=yes cache_valid_time={{ apt_cache_time }}
  with_items:
    - resolvconf
    - dnsmasq

- name: install hostapd
  apt: name={{ item }} state={{ apt_target_state }} force=yes update_cache=yes cache_valid_time={{ apt_cache_time }} default_release=jessie
  with_items:
    - hostapd
    
- name: fix locales
  apt: name={{ item }} state={{ apt_target_state }} force=yes update_cache=yes cache_valid_time={{ apt_cache_time }} default_release=jessie
  with_items:
    - locales
# due to broken dependencies (glibc)

- name: enable services
  service: name={{ item }} enabled=yes
  with_items:
    - hostapd
    - dnsmasq
    
- name: enable ip forwarding
  sysctl: name=net.ipv4.ip_forward value=1 state=present
        
- name: configure interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=644
  tags:
    - toggle_tor

- name: configure ifplugd
  copy: src=ifplugd dest=/etc/default/ifplugd owner=root group=root mode=644
  register: result

- name: restart ifplugd
  service: name=ifplugd state=restarted
  when: result|changed

- name: kill ifplugd wlan process
  shell: "ifplugd -i wlan0 -k"
  register: res
  failed_when: res.rc != 0 and res.rc != 6
  when: result|changed
  
#- name: configure dnsmasq
#  template: src=dnsmasq.j2 dest=/etc/dnsmasq.conf owner=root group=root mode=644
#  notify: restart dnsmasq
#  tags:
#    - toggle_tor
  
- name: configure hostapd
  template: src=hostapd.j2 dest=/etc/hostapd/hostapd.conf owner=root group=root mode=644
  notify: restart hostapd
  register: hostapd_status
  tags:
    - ssid
    - toggle_tor
  
- name: configure hostapd config file path
  template: src=hostapd_default.j2 dest=/etc/default/hostapd owner=root group=root mode=644
  notify: restart hostapd