---
- include: ../../tor/tasks/tor_state.yml tags=ssid,toggle_tor,toggle_silent,network_config

- name: install required packages
  apt: name={{ item }} state={{ apt_target_state }} force=yes update_cache=yes cache_valid_time={{ apt_cache_time }}
  with_items:
    - hostapd
    - wireless-regdb
    - crda
    - iw
    - ifplugd
    - isc-dhcp-server
    - rng-tools

- name: test if hardware rng device exists
  stat:
    path: /dev/hwrng
  register: hwrng_device

- name: disable rngd service
  command: systemctl disable rng-tools.service
  when: hwrng_device.stat.exists == False

- name: enable systemd-networkd service
  command: systemctl enable systemd-networkd.service

#- name: fix locales
#  apt: name={{ item }} state={{ apt_target_state }} force=yes update_cache=yes cache_valid_time={{ apt_cache_time }} default_release=jessie
#  with_items:
#    - locales
# due to broken dependencies (glibc)

- name: create systemd directory for hostapd
  file: path=/etc/systemd/system/hostapd.service.d state=directory

- name: override hostapd systemd dependencies
  copy: src=hostapd-systemd-override dest=/etc/systemd/system/hostapd.service.d/override.conf owner=root group=root mode=644

- name: enable ip forwarding
  sysctl: name=net.ipv4.ip_forward value=1 state=present

- name: enable ip6 forwarding
  sysctl: name=net.ipv6.conf.all.forwarding value=1 state=present

- name: configure interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=644
  register: interfaces
  tags:
    - toggle_tor
    - toggle_silent
    - network_config

- name: configure eth0 interface with networkd
  copy: src=40-eth0.network dest=/etc/systemd/network/40-eth0.network owner=root group=root mode=644
  tags:
    - toggle_tor
    - toggle_silent
    - network_config


- name: check if static ip setup is enabled
  set_fact:
    static_ip_setup: True
  when:
   (ansible_local is defined) and
   (ansible_local.interfaces is defined) and
   (ansible_local.interfaces.general is defined) and
   (ansible_local.interfaces.general.mode is defined) and
   (ansible_local.interfaces.general.mode == "static") and
   (ansible_local.interfaces.static is defined)
  tags:
    - toggle_tor
    - toggle_silent
    - network_config

- name: disable dhcpcd on eth0 for static config
  lineinfile: dest=/etc/dhcpcd.conf regexp=^denyinterfaces\ eth0 line="denyinterfaces eth0" state=present
  when: static_ip_setup is defined
  tags:
    - toggle_tor
    - toggle_silent
    - network_config

- name: re-enable dhcpcd on eth0
  lineinfile: dest=/etc/dhcpcd.conf regexp=^denyinterfaces\ eth0 line="denyinterfaces eth0" state=absent
  when: static_ip_setup is not defined
  tags:
    - toggle_tor
    - toggle_silent
    - network_config

- name: configure ifplugd
  copy: src=ifplugd dest=/etc/default/ifplugd owner=root group=root mode=644
  register: result

- name: restart ifplugd
  service: name=ifplugd state=restarted
  when: result|changed

- name: kill ifplugd wlan process
  shell: "ifplugd -i wlan0 -k"
  register: res
  failed_when: res.rc != 0 and res.rc != 6
  when: result|changed

- name: configure hostapd
  template: src=hostapd.j2 dest=/etc/hostapd/hostapd.conf owner=root group=root mode=644
  notify: restart hostapd
  register: hostapd_status
  tags:
    - ssid
    - toggle_tor
    - toggle_silent

- name: configure hostapd config file path
  template: src=hostapd_default.j2 dest=/etc/default/hostapd owner=root group=root mode=644
  notify: restart hostapd

- name: create systemd directory for isc-dhcp-server
  file: path=/etc/systemd/system/isc-dhcp-server.service.d state=directory

- name: override isc-dhcp-server systemd dependencies
  copy: src=isc-dhcp-systemd-override dest=/etc/systemd/system/isc-dhcp-server.service.d/override.conf owner=root group=root mode=644

- name: set dhcp network interfaces
  template: src=isc-dhcp-server.j2 dest=/etc/default/isc-dhcp-server owner=root group=root mode=644
  notify: restart isc-dhcp-server
  tags:
    - toggle_tor
    - toggle_silent

- name: set dhcp ip ranges
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf owner=root group=root mode=644
  tags:
    - toggle_tor
    - toggle_silent

- name: enable services
  service: name={{ item }} enabled=yes
  with_items:
    - hostapd
    - isc-dhcp-server
  when: tor|bool or silent|bool
  tags:
    - toggle_tor
    - toggle_silent

- name: start services
  service: name={{ item }} state=started
  with_items:
    - hostapd
  when: tor|bool or silent|bool
  tags:
    - toggle_tor
    - toggle_silent

- name: disable services
  service: name={{ item }} enabled=no
  with_items:
    - hostapd
    - isc-dhcp-server
  when: not (tor|bool or silent|bool)
  tags:
    - toggle_tor
    - toggle_silent

- name: stop services
  service: name={{ item }} state=stopped
  with_items:
    - hostapd
  when: not (tor|bool or silent|bool)
  tags:
    - toggle_tor
    - toggle_silent
