---

- include: ../../tor/tasks/tor_state.yml tags=ssid,toggle_tor,toggle_silent,network_config,dhcp_server,configure_devices,wlan_device

- debug:
    msg: "{{ ansible_interfaces }}"
  tags:
    - wlan_device

- set_fact:
    devices: '[{% for dev in ansible_interfaces if "wlan" in dev %}"{{ dev }}",{% endfor %}]'

- name: retrieve kernel module name from wlan0
  stat:
    path: "/sys/class/net/wlan0/device/driver/module"
  when: "'wlan0' in devices"
  register: driver_internal

- set_fact:
    plugged: >
        {{ (devices|length >= 2 and driver_internal is defined and driver_internal.stat.islnk is defined
        and driver_internal.stat.islnk and driver_internal.stat.lnk_source | basename == 'brcmfmac' and 'wlan0'in devices) }}

- debug:
    msg: "{{ devices|length }}"

- debug:
    msg: "{{ plugged }}"

- name: disable internal wlan device
  modprobe: name=brcmfmac state=absent
  when: plugged|bool
  notify:
    - restart hostapd
    - restart isc-dhcp-server

- name: persistently disable internal wlan device
  copy: src=disable_rpi3_wifi.conf dest=/etc/modprobe.d/disable_rpi3_wifi.conf mode=0644 owner=root group=root
  when: plugged|bool
  notify:
    - restart hostapd
    - restart isc-dhcp-server

- name: retrieve kernel module name from wlan1
  stat:
    path: "/sys/class/net/wlan1/device/driver/module"
  when: plugged|bool and 'wlan1' in devices
  register: driver

- name: remove kernel module from wlan1
  modprobe: name="{{ driver.stat.lnk_source | basename }}" state=absent
  when: driver.stat.islnk is defined and driver.stat.islnk and plugged|bool
  notify:
    - restart hostapd
    - restart isc-dhcp-server

- pause: seconds=3
  when: plugged|bool

- name: reinstall kernel module from wlan1
  modprobe: name="{{ driver.stat.lnk_source | basename }}" state=present
  when: driver.stat.islnk is defined and driver.stat.islnk and plugged|bool
  notify:
    - restart hostapd
    - restart isc-dhcp-server

- name: wait for wlan device to be ready
  wait_for:
    path: "/sys/class/net/wlan0"
  when: plugged|bool
  notify:
    - restart hostapd
    - restart isc-dhcp-server
# revert changes

- name: persistently enable internal wlan device
  file: path=/etc/modprobe.d/disable_rpi3_wifi.conf state=absent
  when: not plugged|bool and 'wlan0' not in devices

- name: enable internal wlan device
  modprobe: name=brcmfmac state=present
  when: not plugged|bool and 'wlan0' not in devices
  notify:
    - restart hostapd
    - restart isc-dhcp-server

- name: remove lock file
  file: path=/var/run/wlan.lock state=absent
