---
#jinja2 has to evaluate this string seperately, because it is not possible to just include this string in a "when" statement
- set_fact:
    silent: "{{ default_settings.wlan.general.enabled if not (ansible_local is defined and ansible_local.wlan is defined and ansible_local.wlan.general is defined) else ansible_local.wlan.general.enabled | default(default_settings.wlan.general.enabled) }}"