---
- name: install unattended upgrades
  apt: name={{ item }} state={{ apt_target_state }} force=yes update_cache=yes cache_valid_time={{ apt_cache_time }}
  with_items:
    - unattended-upgrades
    
- name: copy the unattended-upgrades config file
  template: src=02periodic dest=/etc/apt/apt.conf.d/02periodic owner=root group=root mode=0644