---
- name: restart uwsgi
  service: name=django-uwsgi state=restarted

- name: reload uwsgi
  file: path=/etc/uwsgi/upri_uwsgi.ini state=touch

- name: restart supervisor
  service: name=supervisor state=restarted sleep=5
