---
- name: restart uwsgi
  service: name=django-uwsgi state=restarted
  notify: restart registrar

- name: reload uwsgi
  file: path=/etc/uwsgi/upri_uwsgi.ini state=touch
  notify: restart registrar

- name: restart supervisor
  service: name=supervisor state=restarted sleep=5 use=service

- name: uninstall django on errors
  pip: name=django state=absent virtualenv=/var/webapp-virtualenv/
  when: django_res|failed
  notify: reinstall django

- name: reinstall django
  pip: requirements=/usr/share/nginx/www-upri-interface/requirements.txt virtualenv=/var/webapp-virtualenv/
  notify: reload uwsgi
