---
- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart networking
  service: name=networking state=restarted
  notify: restart apate

- name: restart hostapd
  shell: service hostapd stop {{ "&& sleep 5 && service hostapd start" if silent|bool else "" }}
  notify: get ip address

- name: get ip address
  shell: "ip addr show wlan0"
  register: ipaddr
  changed_when: true
  notify: fix ip address

# during initial deployment, wlan0 often does not receive an ip address
# this does not happen on subsequent reboots
- name: fix ip address
  shell: "ip addr add dev wlan0 192.168.55.254/24"
  when: ipaddr.stdout.find("192.168.55.254") == -1

- name: restart systemd-networkd
  # shell: systemctl restart systemd-networkd
  systemd: name=systemd-networkd state=restarted daemon-reload=yes

- name: configure isc-dhcp-server
  service: name={{ item }} enabled={{'yes' if silent|bool or (dhcpd|bool and mode=='static') else 'no'}} use=service
  with_items:
    - isc-dhcp-server

- name: restart isc-dhcp-server
  service: name=isc-dhcp-server state={{'restarted' if silent|bool or (dhcpd|bool and mode=='static') else 'stopped'}}

- name: restart avahi
  service: name=avahi-daemon state=restarted
