---
- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart hostapd
  shell: service hostapd stop && sleep 5 && service hostapd start
  notify: get ip address
  
- name: get ip address
  shell: "ip addr show wlan0"
  register: ipaddr
  changed_when: true
  notify: fix ip address

# during initial deployment, wlan0 often does not receive an ip address
# this does not happen on subsequent reboots
- name: fix ip address
  shell: "ip addr add dev wlan0 192.168.55.254/24" 
  when: ipaddr.stdout.find("192.168.55.254") == -1

# somtimes wlan0 isn't added to /run/network/ifstate and it is not possible to use ifdown and ifup
- name: add wlan0 to ifstate
  shell: "echo 'wlan0=wlan0' | tee -a /run/network/ifstate"
  when: ifstate.stdout.find("wlan0=wlan0") == -1

- name: restart isc-dhcp-server
  service: name=isc-dhcp-server state=restarted
