---
- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart hostapd
  service: name=hostapd state=restarted
  notify: get ip address

- name: restart isc-dhcp-server
  service: name=isc-dhcp-server state=restarted
  
- name: get ip address
  shell: "ip addr show wlan0"
  register: ipaddr
  changed_when: true
  notify: fix ip address

# during initial deployment, wlan0 often does not receive an ip address
# this does not happen on subsequent reboots
- name: fix ip address
  shell: "ip addr add dev wlan0 192.168.55.254/24" 
  when: ipaddr.stdout.find("192.168.55.254") == -1 
