---
- name: set hostname
  hostname: name="{{ hostname }}"
  
- name: configure hosts
  copy: src=hosts dest=/etc/hosts owner=root group=root mode=644
  
- name: configure locale
  shell: 'update-locale LC_ALL="en_GB.UTF-8" LANG="en_GB.UTF-8"'
  
- name: create sudo group
  group: name="{{ sudo_group }}" state=present
  
- name: create remote user
  user: name="{{ remote_user }}" shell="{{ remote_user_login_shell }}" groups="{{sudo_group}}" append=yes
  
- name: configure sudoers
  template: src=sudoers.j2 dest=/etc/sudoers validate='visudo -cf %s'
  
- name: add authorized key
  authorized_key: user="{{ remote_user }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: pull_deployment is not defined