---
- include: ssh_state.yml tags=toggle_ssh
- name: configure ssh
  service: name=ssh state='{{ "started" if ssh_enabled|bool else "stopped" }}' enabled='{{ ssh_enabled|bool }}'
  tags:
    - toggle_ssh
   