---
- name: touch crontab files
  shell: touch {{ item.item.dest }}
  with_items:
    - "{{ cron_result.results }}"
  when: item|changed

- name: move daily backups
  shell: /bin/mv /home/upri/upri_backup_*.zip /var/upribox-backups/daily
  ignore_errors: yes
