---
#jinja2 has to evaluate this string seperately, because it is not possible to just include this string in a "when" statement
- set_fact:
    apate_enabled: "{{ default_settings.apate.general.enabled if not (ansible_local is defined and ansible_local.apate is defined and ansible_local.apate.general is defined) else ansible_local.apate.general.enabled | default(default_settings.apate.general.enabled) }}"
