---
- name: set hostname
  hostname: name="{{ hostname }}"
  
- name: configure hosts
  copy: src=hosts dest=/etc/hosts owner=root group=root mode=644

- name: configure locale
  shell: 'update-locale LC_ALL="en_GB.UTF-8" LANG="en_GB.UTF-8"'
  
- name: install sudo, raspi-config and wifi firmware
  apt: name={{ item }} state=present force=yes update_cache=yes cache_valid_time="{{ apt_cache_time }}"
  with_items:
    - sudo 
    - raspi-config
    - firmware-atheros
    - firmware-ralink
  
- name: create sudo group
  group: name="{{ sudo_group }}" state=present
  
- name: create remote user
  user: name="{{ remote_user }}" shell="{{ remote_user_login_shell }}" groups="{{sudo_group}}" append=yes
  
- name: configure sudoers
  template: src=sudoers.j2 dest=/etc/sudoers validate='visudo -cf %s'
  
- name: add authorized key
  authorized_key: user="{{ remote_user }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: pull_deployment is not defined

- name: expand disk space
  command: /usr/bin/raspi-config --expand-rootfs

- name: rebooting raspberry Pi ...
  shell: /bin/sleep 2 && /sbin/reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for raspberry Pi to restart
  local_action:
    wait_for
    host={{ inventory_hostname }}
    port=22
    delay=15
    timeout=300
  sudo: false

- name: disable root account
  command: /usr/bin/passwd -dl root
